export const CONFIG = {
  // Validity & Baseline
  MIN_EI_BMR_RATIO: 0.6,
  MIN_KCAL_FALLBACK: 800,
  MIN_MEALS_PER_DAY: 2,
  MAX_KCAL_PER_DAY: 6000,
  WINDOW_DAYS: 14,
  THRESHOLD_MACRO: 4,
  THRESHOLD_MINERALS: 7,
  THRESHOLD_MICRO: 10,
  REQUIRE_WEEKEND_DAY: true,
  
  // Daily Review & Insights
  BASELINE_WINDOW: 14,
  MIN_BASELINE_POINTS: 3,
  REPEAT_THRESHOLD: 3,
  SPIKE_SD: 1.5,
  MIN_PAIRS: 5,
  INSIGHT_COOLDOWN: 3,
  
  // Engagement & Schedule
  ONBOARD_GRACE: 5,
  RECOVERY_STREAK: 3,
  NUDGE_COOLDOWN: 3,
  SYNC_GRACE_HOURS: 3,
  MAX_REPORT_ITEMS: 5,
};
