#!/usr/bin/expect -f
set timeout 10
set host "92.63.99.117"
set user "root"
set password "MedMail1981"
set pubkey "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDKd4sv4ePIjq2hD395+yms55SIhmY80gNe+gO5F6bjYXEXiSZQnBfjEYevec+LL6lF6pkyUhMCnqamCXpAjXxx8wHchj1O4BCF6H1RNxnIeDTyKvMhmGdnYaazhl/gu72u8l5XcTWLBaOXhY1ALrcE+SkmcuDTn5+XLR2ODaxhzvwoUFwP/g45C8KF7IzAp5ZgD6f5I/ErJt6uLxQrM9PvJIeuuhdikfN6NnuZCPR9TxxqiUk+WsEcK90OtS3LsuERPgclDj7tnEY8cyTHii4lGXkz19Tr6H1+hYuTqxp0gIsYvQORFMwXmovGuM0rOzetaxilmuyWcPTYR0hL5ZlIoGP3oGMfieOr1QBDIAeGZ7tDixA0y3pVp5kXRMBXIYv5F2nYneohwFi2P2iZA+s0p3HceFk52DUOB17ZXpAuw2/aWCSEf6kwYOJ2+pP5yKWynnJLqS6cw6p0PxTHa8T0/LIpvKiVoGM5IgvxLG5zjTYusAfzJlQ5td9Z9nqi9SbsjN03ePOj7monD0vpZvhRCF0zsHHpzEqY/Sl1TZ1s4Y58dgmXOyQc9vII077lUuoquQj53ZxBWvm2OAweA/Yku44rVWrPCw8oM6Z7XYO5vXbYmKLA96hdhZA9Vq11ElS4BosT5u2w5OfVBubGTZo+2smAPgiIX60a6I5+cesJVw== mogilevandrei@MacBook-Pro-Andrey-2.local"

spawn ssh -o StrictHostKeyChecking=no $user@$host
expect {
    "password:" {
        send "$password\r"
    }
}
expect {
    "#" {
        send "mkdir -p ~/.ssh && chmod 700 ~/.ssh\r"
        send "echo '$pubkey' >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys\r"
        send "echo 'SSH_SETUP_OK'\r"
        send "exit\r"
    }
}
expect eof
